#### Manupulating Tensors

In [1]:
import tensorflow as tf

c:\Users\Hp\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\export\tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):


In [2]:
tf.__version__

'2.20.0'

In [3]:
tensor1 = tf.constant([[1,2],[3,4],[5,6]])
tensor2 = tf.constant([[1,2,3],[4,5,6]])

In [13]:
tensor1

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]])>

In [14]:
tensor2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [17]:
tensor_mod=tf.transpose(tensor1)
tensor_mod

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]])>

In [29]:
tensor_final_0=tf.tensordot(tf.reshape(tensor1,shape=(2,3)),tensor2,axes=0)
tensor_final_0

<tf.Tensor: shape=(2, 3, 2, 3), dtype=int32, numpy=
array([[[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 2,  4,  6],
         [ 8, 10, 12]],

        [[ 3,  6,  9],
         [12, 15, 18]]],


       [[[ 4,  8, 12],
         [16, 20, 24]],

        [[ 5, 10, 15],
         [20, 25, 30]],

        [[ 6, 12, 18],
         [24, 30, 36]]]])>

In [30]:
tensor_final_1=tf.tensordot(tensor_mod,tensor2,axes=0)
tensor_final_1

<tf.Tensor: shape=(2, 3, 2, 3), dtype=int32, numpy=
array([[[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 3,  6,  9],
         [12, 15, 18]],

        [[ 5, 10, 15],
         [20, 25, 30]]],


       [[[ 2,  4,  6],
         [ 8, 10, 12]],

        [[ 4,  8, 12],
         [16, 20, 24]],

        [[ 6, 12, 18],
         [24, 30, 36]]]])>

In [31]:
print({
    "Result through reshaping" :tensor_final_0,
    "Result through Transpose" :tensor_final_1
})

{'Result through reshaping': <tf.Tensor: shape=(2, 3, 2, 3), dtype=int32, numpy=
array([[[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 2,  4,  6],
         [ 8, 10, 12]],

        [[ 3,  6,  9],
         [12, 15, 18]]],


       [[[ 4,  8, 12],
         [16, 20, 24]],

        [[ 5, 10, 15],
         [20, 25, 30]],

        [[ 6, 12, 18],
         [24, 30, 36]]]])>, 'Result through Transpose': <tf.Tensor: shape=(2, 3, 2, 3), dtype=int32, numpy=
array([[[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 3,  6,  9],
         [12, 15, 18]],

        [[ 5, 10, 15],
         [20, 25, 30]]],


       [[[ 2,  4,  6],
         [ 8, 10, 12]],

        [[ 4,  8, 12],
         [16, 20, 24]],

        [[ 6, 12, 18],
         [24, 30, 36]]]])>}


*Difference in both reshape and the transpose*

In [37]:
tensor_X = tensor_final_1-tensor_final_0
tensor_X

<tf.Tensor: shape=(2, 3, 2, 3), dtype=int32, numpy=
array([[[[  0,   0,   0],
         [  0,   0,   0]],

        [[  1,   2,   3],
         [  4,   5,   6]],

        [[  2,   4,   6],
         [  8,  10,  12]]],


       [[[ -2,  -4,  -6],
         [ -8, -10, -12]],

        [[ -1,  -2,  -3],
         [ -4,  -5,  -6]],

        [[  0,   0,   0],
         [  0,   0,   0]]]])>

In [39]:
tensor_final_2 = tf.tensordot(tensor1,tf.transpose(tensor2),axes=0)
tensor_final_2

<tf.Tensor: shape=(3, 2, 3, 2), dtype=int32, numpy=
array([[[[ 1,  4],
         [ 2,  5],
         [ 3,  6]],

        [[ 2,  8],
         [ 4, 10],
         [ 6, 12]]],


       [[[ 3, 12],
         [ 6, 15],
         [ 9, 18]],

        [[ 4, 16],
         [ 8, 20],
         [12, 24]]],


       [[[ 5, 20],
         [10, 25],
         [15, 30]],

        [[ 6, 24],
         [12, 30],
         [18, 36]]]])>

In [42]:
tensor_final_3 = tf.tensordot(tensor1,tf.reshape(tensor2,(3,2)),axes=0)
tensor_final_3

<tf.Tensor: shape=(3, 2, 3, 2), dtype=int32, numpy=
array([[[[ 1,  2],
         [ 3,  4],
         [ 5,  6]],

        [[ 2,  4],
         [ 6,  8],
         [10, 12]]],


       [[[ 3,  6],
         [ 9, 12],
         [15, 18]],

        [[ 4,  8],
         [12, 16],
         [20, 24]]],


       [[[ 5, 10],
         [15, 20],
         [25, 30]],

        [[ 6, 12],
         [18, 24],
         [30, 36]]]])>

In [43]:
tensor_Y = tensor_final_3 - tensor_final_2
tensor_Y

<tf.Tensor: shape=(3, 2, 3, 2), dtype=int32, numpy=
array([[[[  0,  -2],
         [  1,  -1],
         [  2,   0]],

        [[  0,  -4],
         [  2,  -2],
         [  4,   0]]],


       [[[  0,  -6],
         [  3,  -3],
         [  6,   0]],

        [[  0,  -8],
         [  4,  -4],
         [  8,   0]]],


       [[[  0, -10],
         [  5,  -5],
         [ 10,   0]],

        [[  0, -12],
         [  6,  -6],
         [ 12,   0]]]])>

In [46]:
print({
    "x modified Tensor" : tensor_X,
    "y modified Tensor" : tensor_Y
})

{'x modified Tensor': <tf.Tensor: shape=(2, 3, 2, 3), dtype=int32, numpy=
array([[[[  0,   0,   0],
         [  0,   0,   0]],

        [[  1,   2,   3],
         [  4,   5,   6]],

        [[  2,   4,   6],
         [  8,  10,  12]]],


       [[[ -2,  -4,  -6],
         [ -8, -10, -12]],

        [[ -1,  -2,  -3],
         [ -4,  -5,  -6]],

        [[  0,   0,   0],
         [  0,   0,   0]]]])>, 'y modified Tensor': <tf.Tensor: shape=(3, 2, 3, 2), dtype=int32, numpy=
array([[[[  0,  -2],
         [  1,  -1],
         [  2,   0]],

        [[  0,  -4],
         [  2,  -2],
         [  4,   0]]],


       [[[  0,  -6],
         [  3,  -3],
         [  6,   0]],

        [[  0,  -8],
         [  4,  -4],
         [  8,   0]]],


       [[[  0, -10],
         [  5,  -5],
         [ 10,   0]],

        [[  0, -12],
         [  6,  -6],
         [ 12,   0]]]])>}


*Generally transpose one of the tensor for satisfy the condition in it* 