***Type Casting on Tensorflow***

In [1]:
import tensorflow as tf

c:\Users\Hp\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\export\tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):


In [2]:
tf.__version__

'2.20.0'

In [3]:
tensor1 = tf.constant([[1,2],[3,4],[5,6]])
tensor2 = tf.constant([[1,2,3],[4,5,6]])

In [4]:
tensor1

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]])>

In [5]:
tf.cast(tensor1,dtype=tf.float16)

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)>

In [6]:
tf.cast(tensor2,dtype=tf.float32)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [7]:
tf.cast(tensor1,dtype=tf.int16)

<tf.Tensor: shape=(3, 2), dtype=int16, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int16)>

#### *End*