#### *Tensor Aggregation*

In [1]:
import tensorflow as tf

c:\Users\Hp\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\export\tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):


In [2]:
tf.__version__

'2.20.0'

*Aggregating Tensor = Reducing a multi-dimensional tensor into a smaller Structure*

In [3]:
tensor1 = tf.constant([-7,-10])

`tf.abs()` - *function that changes the negative values into positive*

In [4]:
tf.abs(tensor1)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10])>

#### *Aggregation Types*
- Get the minimum
- Get the maximum
- Get the mean of the tensor
- Get the sum of the tensor

In [5]:
import numpy as np

In [6]:
tensor2 = tf.constant(np.random.randint(0,100,size = 50))
tensor2

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([64, 99, 68, 98, 57,  5, 37, 62, 18,  8, 38, 81, 13, 99, 82, 53, 31,
       95, 36, 64, 11,  9,  5, 68, 92, 67, 63, 74, 30, 91, 90,  3, 97, 75,
       35, 57, 55, 25, 77, 56, 72, 26, 71, 93, 37, 49, 35, 67,  5, 63])>

In [7]:
#size of the tensor
tf.size(tensor2)

<tf.Tensor: shape=(), dtype=int32, numpy=50>

In [8]:
#shape of the tensor
tensor2.shape

TensorShape([50])

In [9]:
#Dimensions of tensor
tensor2.ndim

1

In [10]:
#Minimum on the tensor
tf.reduce_min(tensor2)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [11]:
#Maximum of the tensor
tf.reduce_max(tensor2)

<tf.Tensor: shape=(), dtype=int32, numpy=99>

In [12]:
#Mean of the Tensor
tf.reduce_mean(tensor2)

<tf.Tensor: shape=(), dtype=int32, numpy=54>

#### *Excercise : Finding the Tensor Standard Deviation and the Variance of tensor2*
- *Both supports only the dtype = float64* 
- *or use tensorflow_probability to make variance and std*

In [13]:
tensor2_fp = tf.cast(tensor2,dtype=tf.float64)
tensor2_fp

<tf.Tensor: shape=(50,), dtype=float64, numpy=
array([64., 99., 68., 98., 57.,  5., 37., 62., 18.,  8., 38., 81., 13.,
       99., 82., 53., 31., 95., 36., 64., 11.,  9.,  5., 68., 92., 67.,
       63., 74., 30., 91., 90.,  3., 97., 75., 35., 57., 55., 25., 77.,
       56., 72., 26., 71., 93., 37., 49., 35., 67.,  5., 63.])>

In [14]:
# Finding std deviation
tf.math.reduce_std(tensor2_fp)

<tf.Tensor: shape=(), dtype=float64, numpy=29.40315629316009>

In [15]:
#Finding variance on tensor2_fp
tf.math.reduce_variance(tensor2_fp)

<tf.Tensor: shape=(), dtype=float64, numpy=864.5455999999999>

In [ ]:
# pip install tensorflow_probability

Note: you may need to restart the kernel to use updated packages.


In [ ]:
# pip install tf_keras

   ---------------------------------------- 0.0/1.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.7 MB ? eta -:--:--
   ---------------------------------------- 1.7/1.7 MB 15.2 MB/s  0:00:00
Note: you may need to restart the kernel to use updated packages.


In [21]:
import tensorflow_probability as tfp

In [24]:
# `Finding Variance with tfp`
tfp.stats.variance(tensor2)

<tf.Tensor: shape=(), dtype=int32, numpy=864>

In [28]:
tensor_x = tf.random.normal(shape=(10,2,3))
tensor_x

<tf.Tensor: shape=(10, 2, 3), dtype=float32, numpy=
array([[[ 0.31205085,  0.0369037 ,  0.6142428 ],
        [ 1.0666077 ,  0.4609918 , -2.2389455 ]],

       [[ 0.791615  ,  0.4912353 ,  0.51102984],
        [ 0.4270419 ,  1.9982015 , -0.7058575 ]],

       [[-1.3663456 , -0.13176852, -0.7865944 ],
        [-1.1180359 , -1.0383273 , -0.1788508 ]],

       [[-0.42780447, -1.0079511 , -0.29851744],
        [-0.34894994,  1.2773664 ,  1.6188012 ]],

       [[ 0.4438939 , -0.6198707 ,  0.9338816 ],
        [-1.1506227 ,  0.23426278,  0.18308544]],

       [[ 0.01290125,  1.5867283 , -0.75740993],
        [ 1.1343787 ,  0.46348208,  0.7702673 ]],

       [[-1.1624756 , -0.4029877 ,  0.1469046 ],
        [-1.3675857 ,  0.05404321,  0.76841843]],

       [[-0.07582542,  0.6584857 ,  0.51294565],
        [ 0.86047876,  0.90253866, -0.20529655]],

       [[-0.28487217, -1.7938406 , -0.71834993],
        [-0.24173197,  0.49598774,  1.1998065 ]],

       [[-1.5024794 , -0.47005364,  1.2328373 ],

In [29]:
tfp.stats.stddev(tensor_x)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.74863344, 0.89103794, 0.7013717 ],
       [0.9079725 , 0.79803765, 1.0516793 ]], dtype=float32)>

#### *`End`*