#### *Finding Positional Maximum and minimum* 

In [1]:
import tensorflow as tf

c:\Users\Hp\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\export\tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):


In [4]:
tf.random.set_seed(42)
tensor1 = tf.random.uniform(shape=[50])
tensor1

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [6]:
# Positonal Maximum of tensor
position_max = tf.argmax(tensor1)
position_max

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [22]:
#Value of Maximum
import pprint
max_value = tensor1[position_max]
pprint.pp({
    "Tensor_Value":max_value,
    "Numpy_Value": max_value.numpy()
})

{'Tensor_Value': <tf.Tensor: shape=(), dtype=float32, numpy=0.967138409614563>,
 'Numpy_Value': 0.9671384}


In [16]:
# Confirming it as True or False 
(max_value == tf.reduce_max(tensor1)).numpy()

True

In [36]:
#Finding the positional minimum
positional_min = tf.argmin(tensor1)
positional_min

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [34]:
min_value = tensor1[positional_min]
min_value

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463667869567871>

In [35]:
tf.reduce_min(tensor1)

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463667869567871>

In [42]:
(min_value == tf.reduce_min(tensor1)).numpy()

True

In [37]:
#Value of Minimum
import pprint
max_value = tensor1[position_max]
pprint.pp({
    "Tensor_Value":min_value,
    "Numpy_Value": min_value.numpy()
})

{'Tensor_Value': <tf.Tensor: shape=(), dtype=float32, numpy=0.009463667869567871>,
 'Numpy_Value': 0.009463668}
