#### *Squeezing Tensors*
- *These removes the extra 1-dimensional thing on the tensors*

In [1]:
import tensorflow as tf

c:\Users\Hp\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\export\tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):


In [4]:
tensor_1 = tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
tensor_1

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.645617  , 0.18695152, 0.882619  , 0.69122577, 0.37045717,
           0.11295891, 0.48603368, 0.41033173, 0.94998443, 0.8951433 ,
           0.08038723, 0.7836137 , 0.8414756 , 0.62805736, 0.39721859,
           0.63647604, 0.0381434 , 0.40942407, 0.02211523, 0.78777254,
           0.80277455, 0.7352674 , 0.02755785, 0.13539875, 0.97848463,
           0.7608268 , 0.110062  , 0.4357525 , 0.6371349 , 0.9100126 ,
           0.9870403 , 0.2772441 , 0.2799753 , 0.9892504 , 0.30469513,
           0.89265096, 0.11776793, 0.10200667, 0.8442389 , 0.14133215,
           0.56210244, 0.23833025, 0.92907   , 0.4847815 , 0.40163767,
           0.6196723 , 0.771649  , 0.14614677, 0.33382058, 0.2873838 ]]]]],
      dtype=float32)>

In [5]:
tensor_1.shape

TensorShape([1, 1, 1, 1, 50])

In [6]:
tensor_1_squeeze = tf.squeeze(tensor_1)
tensor_1_squeeze

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.645617  , 0.18695152, 0.882619  , 0.69122577, 0.37045717,
       0.11295891, 0.48603368, 0.41033173, 0.94998443, 0.8951433 ,
       0.08038723, 0.7836137 , 0.8414756 , 0.62805736, 0.39721859,
       0.63647604, 0.0381434 , 0.40942407, 0.02211523, 0.78777254,
       0.80277455, 0.7352674 , 0.02755785, 0.13539875, 0.97848463,
       0.7608268 , 0.110062  , 0.4357525 , 0.6371349 , 0.9100126 ,
       0.9870403 , 0.2772441 , 0.2799753 , 0.9892504 , 0.30469513,
       0.89265096, 0.11776793, 0.10200667, 0.8442389 , 0.14133215,
       0.56210244, 0.23833025, 0.92907   , 0.4847815 , 0.40163767,
       0.6196723 , 0.771649  , 0.14614677, 0.33382058, 0.2873838 ],
      dtype=float32)>

`End`