### *Math-Operations = `Squaring, log, & Square_roots`*

In [1]:
import tensorflow as tf

c:\Users\Hp\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\export\tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):


In [5]:
#Creating new Tensor
tensor_1 = tf.range(start=1,limit=11)
tensor_1

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])>

In [6]:
#Square of the tensors
tf.square(tensor_1)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])>

*Type-Casting for `tf.sqrt()` which is compact with float16,float32*

In [ ]:
tensor_fp = tf.cast(tensor_1,dtype=tf.float16)
tensor_fp

<tf.Tensor: shape=(10,), dtype=float16, numpy=array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float16)>

In [16]:
# Tensor Square root
tf.sqrt(tensor_fp)

<tf.Tensor: shape=(10,), dtype=float16, numpy=
array([1.   , 1.414, 1.732, 2.   , 2.236, 2.45 , 2.646, 2.828, 3.   ,
       3.162], dtype=float16)>

In [19]:
#tensor log also supports only float
tf.math.log(tensor_fp)

<tf.Tensor: shape=(10,), dtype=float16, numpy=
array([0.    , 0.6934, 1.099 , 1.387 , 1.609 , 1.792 , 1.946 , 2.08  ,
       2.197 , 2.303 ], dtype=float16)>

*`End`*