#### ***Tensorflow and Numpy Compatability***

In [2]:
import tensorflow as tf
import numpy as np

In [4]:
# Creating a Tensor Array
tensor_1 = tf.constant(np.arange(10))
tensor_1

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [5]:
import pprint
pprint.pp({
    "Tensor":tensor_1,
    "Numpy Array": np.array(tensor_1)
})

{'Tensor': <tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>,
 'Numpy Array': array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])}


In [8]:
tensor_np = np.array(tensor_1)
tensor_np,type(tensor_np)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), numpy.ndarray)

In [13]:
#converting numpy_arrays into tensors
np_tensor = tf.constant(tensor_np)
np_tensor.numpy()[8]

8

***Checking Each of the datatypes of numpy and the tensorflow's tensors***

In [22]:
numpy_tensor = tf.constant(np.array([3.,4.,5.,6.,7.,8.]))
normal_tensor = tf.constant([3.,4.,5.,6.,7.,8.])

In [23]:
#Checking dtypes of tensors
pprint.pp({
    "dtypes of numpy_tensor":numpy_tensor.dtype,
    "dtypes of normal_tensor":normal_tensor.dtype
})

{'dtypes of numpy_tensor': tf.float64, 'dtypes of normal_tensor': tf.float32}


***Finding CPU and GPU on the device***

In [29]:
#listing all the devices which present as physical
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [31]:
#listing all the GPU on the device
tf.config.list_physical_devices("GPU")

[]

***End***