In [1]:
pip install tensorflow

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.3 -> 26.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import tensorflow as tf


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.3.5 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Hp\AppData\Roaming\Python\Python312\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "C:\Users\Hp\AppData\Roaming\Python\Python312\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\Users\Hp\AppData\Roaming\Python\Python312\site-packages\ipykernel\kernelapp.py", line 758, in start
    self.io_loop.start(

AttributeError: _ARRAY_API not found

c:\Users\Hp\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\export\tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):


In [ ]:
print(tf.__version__)

2.20.0


#### Creating Variables using tf.constant

In [7]:
scalar = tf.constant(7)

In [11]:
print({
    "Value": scalar,
    "Dimension":scalar.ndim
})


{'Value': <tf.Tensor: shape=(), dtype=int32, numpy=7>, 'Dimension': 0}


In [14]:
vector = tf.constant([1,2,3,4,5])

In [15]:
print({
    "Value": vector,
    "Dimension":vector.ndim
})

{'Value': <tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>, 'Dimension': 1}


In [16]:
matrix=tf.constant([
    [7,10],
    [10,7]
])

In [17]:
print({
    "Value": matrix,
    "Dimension":matrix.ndim
})

{'Value': <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [10,  7]], dtype=int32)>, 'Dimension': 2}


In [19]:
tensor = tf.constant([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])

In [20]:
print({
    "Value": tensor,
    "Dimension":tensor.ndim
})

{'Value': <tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>, 'Dimension': 3}
