### Getting Information from Tensors
- Rank
- Shape
- Size
- Dimension

In [1]:
import tensorflow as tf

c:\Users\Hp\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\export\tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):


In [5]:
#creating rank 4 tensor 
tensor4 = tf.ones(shape=(2,3,4,5))
tensor4

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]], dtype=float32)>

In [6]:
tensor4[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]], dtype=float32)>

In [7]:
#shape
tensor4.shape

TensorShape([2, 3, 4, 5])

In [10]:
#Dimensions
tensor4.ndim

4

In [11]:
#size
tf.size(tensor4)

<tf.Tensor: shape=(), dtype=int32, numpy=120>

In [16]:
print("Datatype of Tensors : ",tensor4.dtype)
print("Number of Dimensions (rank): ",tensor4.ndim)
print("Shape of Tensors : ",tensor4.shape)
print("Elements on 0 axis : ",tensor4.shape[0])
print("Elements on last axis : ",tensor4.shape[-1])
print("Total Number of Tensors : ",tf.size(tensor4))
print("Total Number of Tensors : ",tf.size(tensor4).numpy())

Datatype of Tensors :  <dtype: 'float32'>
Number of Dimensions (rank):  4
Shape of Tensors :  (2, 3, 4, 5)
Elements on 0 axis :  2
Elements on last axis :  5
Total Number of Tensors :  tf.Tensor(120, shape=(), dtype=int32)
Total Number of Tensors :  120
