In [3]:
import tensorflow as tf

In [4]:
tf.__version__

'2.20.0'

#### Indexing Tensors
- Indexing can be happen like python lists

In [6]:
tensor4 = tf.ones(shape=(2,3,4,5))
tensor4

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]], dtype=float32)>

In [7]:
tensor4[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]]], dtype=float32)>

In [11]:
tensor4[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[1., 1., 1., 1., 1.]]]], dtype=float32)>

In [12]:
tensor4[:1,:1,:,:]


<tf.Tensor: shape=(1, 1, 4, 5), dtype=float32, numpy=
array([[[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]], dtype=float32)>

In [13]:
tensor4[:1,:1,:,:1]


<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[1.],
         [1.],
         [1.],
         [1.]]]], dtype=float32)>

In [17]:
tensor2=tf.constant([
    [10,2],
    [7,10]
])
tensor2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  2],
       [ 7, 10]])>

In [23]:
#last Item on the list
tensor2[-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10])>

In [24]:
#upgrading rank 2 tensor into rank 3 tensor
tensor3 = tensor2[...,tf.newaxis]
tensor3

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 2]],

       [[ 7],
        [10]]])>

In [29]:
#alternative to tf.newaxis
tensor3 = tf.expand_dims(tensor2,axis=-1)
tensor3

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 2]],

       [[ 7],
        [10]]])>

In [30]:
tensor3 = tf.expand_dims(tensor2,axis=0)
tensor3

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  2],
        [ 7, 10]]])>

##### End