### Manupulating Tensors

In [1]:
import tensorflow as tf

c:\Users\Hp\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\export\tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):


#### Addition

In [8]:
tensor1 = tf.constant([[10,7],[7,10]])
# tensor1 = tensor1+10
tensor1 + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [17, 20]])>

In [9]:
tensor1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

#### Subraction

In [12]:
tensor1 - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-3,  0]])>

#### Multiplication

In [13]:
tensor1 * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 70, 100]])>

#### Division

In [14]:
tensor1 / 10

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 0.7],
       [0.7, 1. ]])>

#### Built-in Functions

In [18]:
# Addition
print("tf.add")
print(tf.add(tensor1, 100))
#Subraction
print("tf.subract")
print(tf.subtract(tensor1, 10))
#Multiplication
print("tf.multiply")
print(tf.multiply(tensor1, 100))
#Division
print("tf.divide")
print(tf.divide(tensor1,5))

tf.add
tf.Tensor(
[[110 107]
 [107 110]], shape=(2, 2), dtype=int32)
tf.subract
tf.Tensor(
[[ 0 -3]
 [-3  0]], shape=(2, 2), dtype=int32)
tf.multiply
tf.Tensor(
[[1000  700]
 [ 700 1000]], shape=(2, 2), dtype=int32)
tf.divide
tf.Tensor(
[[2.  1.4]
 [1.4 2. ]], shape=(2, 2), dtype=float64)


#### Matrix Multiplications

In [19]:
tensor2 = tf.constant([[10,11],[12,14]])
tensor2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 11],
       [12, 14]])>

In [23]:
tf.matmul(tensor1,tensor2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[184, 208],
       [190, 217]])>

In [24]:
tensor1 @ tensor2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[184, 208],
       [190, 217]])>

In [27]:
tensor3 = tf.constant([[1,2],[3,4],[5,6]])
tensor3

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]])>

In [30]:
tensor4= tf.constant([[1,2,3],[4,5,6]])
tensor4

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [45]:
tensor_ans = tf.matmul(tensor1,tf.reshape(tensor3,shape=(2,3)))
tensor_ans

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[38, 55, 72],
       [47, 64, 81]])>

In [47]:
tensor_ans_1 = tf.matmul(tensor1,tensor3,transpose_b=True)
tensor_ans_1

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[24, 58, 92],
       [27, 61, 95]])>

#### End