#### Dot-Product(Matrix Multiplication)
- *Matrix Multiplication also referred as dot product*
- **tf.matmul()**
- **tf.tensordot()**

In [1]:
import tensorflow as tf

c:\Users\Hp\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\export\tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):


In [2]:
tensor1 = tf.constant([[1,2,3],[4,5,6]])
tensor2 = tf.constant([[1,2],[3,4],[5,6]])

In [3]:
tensor1,tensor2

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>)

In [18]:
tensor_mod = tf.reshape(tensor2,shape=(2,3))
tensor_mod

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [37]:
tf.matmul(tensor1,tf.reshape(tensor2,shape=(2,3)),transpose_a=True)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])>

In [35]:
tensor1=tf.reshape(tensor1,(2,3))
tensor1

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [38]:
tensormul = tf.tensordot(tf.reshape(tensor1,(2,3)),tensor2,axes=1)
tensormul

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[22, 28],
       [49, 64]])>

#### End