#### Changing Datatypes of Tensors

In [1]:
import tensorflow as tf

c:\Users\Hp\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\export\tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):


In [4]:
tensor1= tf.constant([[1.7,2.7],[3.2,4.1]])
print(tensor1)

tf.Tensor(
[[1.7 2.7]
 [3.2 4.1]], shape=(2, 2), dtype=float32)


In [8]:
tensor_mod = tf.cast(tensor1,dtype=tf.float16)
tensor_mod

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[1.7, 2.7],
       [3.2, 4.1]], dtype=float16)>

In [9]:
tf.cast(tensor_mod,dtype=tf.int32)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [11]:
tf.cast(tensor_mod,dtype=tf.float16)

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[1.7, 2.7],
       [3.2, 4.1]], dtype=float16)>

#### End