#### Manupulating Tensors (Basic Operations)
- ***Basic operations***

In [1]:
import tensorflow as tf

c:\Users\Hp\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\export\tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):


In [2]:
tensor1 = tf.constant([[1,2],[3,4]])
tensor1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [3]:
tensor1+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14]])>

In [6]:
tensor1 = tensor1+10
tensor1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[21, 22],
       [23, 24]])>

In [7]:
tensor1 - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14]])>

#### End