In [1]:
import tensorflow as tf

In [2]:
import numpy as np

In [41]:
x = np.array([1., 3., 5., 7., 9., 11.,13.,15.], dtype="float32")
y = np.array([2., 4., 6., 8., 10., 12.,14.,16.], dtype="float32")
x = x.reshape(-1, 1)

In [42]:
X= tf.cast(x,dtype=tf.float32)
Y= tf.cast(y,dtype=tf.float32)
X,Y

(<tf.Tensor: shape=(8, 1), dtype=float32, numpy=
 array([[ 1.],
        [ 3.],
        [ 5.],
        [ 7.],
        [ 9.],
        [11.],
        [13.],
        [15.]], dtype=float32)>,
 <tf.Tensor: shape=(8,), dtype=float32, numpy=array([ 2.,  4.,  6.,  8., 10., 12., 14., 16.], dtype=float32)>)

In [43]:
# Basic Model
basic_model = tf.keras.Sequential([
    tf.keras.layers.Dense(1)
])

In [44]:
#model compiling
basic_model.compile(loss=tf.keras.losses.mae,optimizer=tf.keras.optimizers.Adam(),metrics=["mae"])

In [45]:
# Fitting the Model
basic_model.fit(X,Y,epochs=10)

Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 488ms/step - loss: 0.4745 - mae: 0.4745
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 0.4705 - mae: 0.4705
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 0.4665 - mae: 0.4665
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - loss: 0.4625 - mae: 0.4625
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 0.4585 - mae: 0.4585
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - loss: 0.4545 - mae: 0.4545
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - loss: 0.4505 - mae: 0.4505
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - loss: 0.4465 - mae: 0.4465
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - loss: 0.4436 - mae: 0.4436
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - loss: 0.4418 - mae: 0.4418


In [46]:
y_pred = basic_model.predict(x)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step


In [47]:
y_pred

array([[ 1.1098932],
       [ 3.3274   ],
       [ 5.5449066],
       [ 7.762414 ],
       [ 9.97992  ],
       [12.197428 ],
       [14.414934 ],
       [16.632442 ]], dtype=float32)

In [48]:
# Model with higher Number of layers compared to the basic model

In [49]:
improved_model = tf.keras.Sequential([
    tf.keras.layers.Dense(100,activation="relu"),
    tf.keras.layers.Dense(1),
])

In [50]:
#Compiling the Improved Model
improved_model.compile(loss=tf.keras.losses.mae,optimizer=tf.keras.optimizers.SGD(),metrics=["mae"])

In [62]:
#Fitting Model
improved_model.fit(x,y,epochs=50)

Epoch 1/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - loss: 1.0399 - mae: 1.0399
Epoch 2/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - loss: 0.7015 - mae: 0.7015
Epoch 3/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 0.9847 - mae: 0.9847
Epoch 4/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 0.5888 - mae: 0.5888
Epoch 5/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - loss: 1.1005 - mae: 1.1005
Epoch 6/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - loss: 0.6356 - mae: 0.6356
Epoch 7/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - loss: 1.0426 - mae: 1.0426
Epoch 8/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - loss: 0.6822 - mae: 0.6822
Epoch 9/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - loss: 0.9852 - mae: 0.9852
Epoch 10/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - loss: 0.7285 - mae: 0.7285
Epoch 11/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 0.9316 - mae: 0.9316
Epoch 12/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 0.6172 - mae: 0.6172
Epoch 13/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 1.0

In [52]:
x,y

(array([[ 1.],
        [ 3.],
        [ 5.],
        [ 7.],
        [ 9.],
        [11.],
        [13.],
        [15.]], dtype=float32),
 array([ 2.,  4.,  6.,  8., 10., 12., 14., 16.], dtype=float32))

In [67]:
test = np.array([10.0]).reshape(-1,1)

In [68]:
y_pred = improved_model.predict(test)
y_pred

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step


array([[12.012304]], dtype=float32)